"""AI 辅助研判模块。"""

try:
    from .judgement import (
        AISettings,
        LocalJinaRuntime,
        build_ai_detail,
        create_jina_offline_package,
        deploy_jina_package,
        fetch_llm_models,
        fetch_llm_models_result,
        import_jina_model,
        jina_deployment_status,
        load_ai_settings,
        online_deploy_jina,
        resolve_llama_server_asset,
        run_ai_judgement,
        save_ai_settings,
        settings_from_dict,
        test_embedding,
        test_llm,
        test_llm_result,
        wait_for_embedding_ready,
    )
except ImportError:  # 兼容 cd upper_computer 后直接 python main.py
    if __package__ and __package__.startswith("upper_computer"):
        raise
    from judgement import (  # type: ignore
        AISettings,
        LocalJinaRuntime,
        build_ai_detail,
        create_jina_offline_package,
        deploy_jina_package,
        fetch_llm_models,
        fetch_llm_models_result,
        import_jina_model,
        jina_deployment_status,
        load_ai_settings,
        online_deploy_jina,
        resolve_llama_server_asset,
        run_ai_judgement,
        save_ai_settings,
        settings_from_dict,
        test_embedding,
        test_llm,
        test_llm_result,
        wait_for_embedding_ready,
    )

__all__ = [
    "AISettings",
    "LocalJinaRuntime",
    "build_ai_detail",
    "create_jina_offline_package",
    "deploy_jina_package",
    "fetch_llm_models",
    "fetch_llm_models_result",
    "import_jina_model",
    "jina_deployment_status",
    "load_ai_settings",
    "online_deploy_jina",
    "resolve_llama_server_asset",
    "run_ai_judgement",
    "save_ai_settings",
    "settings_from_dict",
    "test_embedding",
    "test_llm",
    "test_llm_result",
    "wait_for_embedding_ready",
]
